apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazel-cache
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/bazel-cache/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bazel-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: bazel
spec:
  containers:
  - name: bazel
    image: gcr.io/istio-testing/ubuntu-16-04-slave:latest
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /pilot
      name: host-mount
    - mountPath: /home/jenkins/.cache
      name: bazel-cache
    - mountPath: /var/run/docker.sock
      name: docker-sock
    resources:
      requests:
        cpu: 1000m
    securityContext:
      privileged: true
  volumes:
  - name: host-mount
    hostPath:
      path: /pilot
  - name: bazel-cache
    persistentVolumeClaim:
      claimName: bazel-cache
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
